//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session6Desktop.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public long ID { get; set; }
        public long OrderID { get; set; }
        public long PartID { get; set; }
        public string BatchNumber { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Stock { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Parts Parts { get; set; }
    }
}
